using OnlineAccountingServer.Domain.AppEntities;
using OnlineAccountingServer.Domain.Repositories.GenericRepositories.AppDbContext;


namespace OnlineAccountingServer.Domain.Repositories.AppDbContext.MainRoleAndUserRelationshipRepositories;

public interface IMainRoleAndUserRelationshipQueryRepository : IAppQueryRepository<MainRoleAndUserRelationship>
{

}
