using OnlineAccountingServer.Domain.AppEntities;
using OnlineAccountingServer.Persistance.Repositories.GenericRepositories.AppDbContext;
using OnlineAccountingServer.Domain.Repositories.AppDbContext.MainRoleAndUserRelationshipRepositories;

namespace OnlineAccountingServer.Persistance.Repositories.AppDbContext.MainRoleAndUserRelationshipRepositories;

public class MainRoleAndUserRelationshipQueryRepository : AppQueryRepository<MainRoleAndUserRelationship>, IMainRoleAndUserRelationshipQueryRepository
{
    public MainRoleAndUserRelationshipQueryRepository(Persistance.Context.AppDbContext context) : base(context){ }
}
